# Generated by Django 4.0.3 on 2023-10-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
