# Generated by Django 4.0.3 on 2023-10-24 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_appointment_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='employee_id',
        ),
    ]
